@startuml UML-projet agile

!include ./theme.puml

skinparam classAttributeIconSize 0
skinparam ClassFontSize 20
skinparam DefaultFontSize 16
skinparam WrapWidth 700
skinparam ArrowFontSize 20
skinparam ArrowThickness 3
skinparam DefaultFontColor white


skinparam Nodesep 100
skinparam Ranksep 100

enum Color {
    TREFLE
    PIQUE
    COEUR
    CARREAU
}

enum Rank {
    DEUX(2)
    TROIS(3)
    QUATRE(4)
    CINQ(5)
    SIX(6)
    SEPT(7)
    HUIT(8)
    NEUF(9)
    VALET(10)
    ROI(13)
    DAME(12)
    ACE(1)
}

class Card {
    - rank : Rank
    - color: Color
    ----
    ..Constructor..
    + getRank()
    + getColor()
    + toString()
    ....
}



@enduml